### ISSUE TITLE
How are currency systems expected to be implemented in practice?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#343] opened 2016-11-30 03:43 UTC
The currencySystem member of PaymentRequest is .... very open-ended.  What are UAs supposed to do with this in practice so that there is some semblance of interop?  Is there a set of currency systems that must be supported (e.g. at least ISO 4217)?  What does support mean?

**Comment by marcoscaceres** [comment] 2016-11-30 03:45
Related to: https://github.com/w3c/browser-payment-api/issues/305

**Comment by bzbarsky** [comment] 2016-11-30 03:47
Looks like this is a dup, then.

**Comment by zkoch** [comment] 2016-12-01 00:09
Given this is a dupe of #305 which is closed, any objection to closing this one?

**Comment by marcoscaceres** [comment] 2016-12-01 01:41
We can, but I'm concerned this is going to keep coming up. That should be setting off alarm bells. 

 I fear we've come up with an inadequate compromise to appease a portion of the community - but without fully thinking through the implications of this design decision. 

This may come back to bite us later :( let's close it, but someone else raises this again - we will need to deal with it. 

Perhaps we should mention in the spec that currencySystem is controversial.

**Comment by zkoch** [comment] 2016-12-01 01:46
I have no objection to raising this issue again. Considering that I don't think we have a single implementation that really uses this, I would be fine with sticking with ISO4217 codes.

**Comment by marcoscaceres** [comment] 2017-02-23 05:21
Closing as duplicate of #305.

**Closed as completed by marcoscaceres** 2017-02-23 05:21 UTC
