### ISSUE TITLE
"User accepts the payment request algorithm" needs to clarify where Payment Handlers are invoked

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#476] opened 2017-03-24 13:07 UTC
Currently the documented algorithm has the following issues;

1. Unclear separation of concerns makes payment handler functionality ambiguous
2. as a result, brittle specification between payment handler spec and payment request spec (changes to algorithm in payment request makes algorithm in payment handlers incorrect) - for example see that in payment handlers, it current states that it replaces steps 6 & 7, whereas this is incorrect and it should be steps 7 & 8 (probably as a result of a removed step in PaymentRequest algorithm).

With the recently matured Payment Handlers specification having specified amendments to this algorithm, I recommend that the algorithm is updated in the PaymentRequest specification to clearly define a separation of concerns  between the mediators and the payment handlers.

**Comment by marcoscaceres** [comment] 2017-03-28 02:04
@mattsaxon, I know you wrote the above during the f2f - so could probably use some cleanup. I'm having a hard time processing what you wrote above. Can you please re-read/write it, and make it a bit more clear.

**Comment by mattsaxonwp** [comment] 2017-04-03 11:03
OK, sure... 2nd try.

In section 7.4, it states that the algorithm replaces steps 6 & 7 in Payment Request. I think this statement is brittle and should say something like this replaces section X in Payment Request.

I would recommend that the algorithm in [Payment Request in section 19.4](https://www.w3.org/TR/payment-request/#user-accepts-the-payment-request-algorithm) be updated to clearly show what is the responsibility of the "mediator" and what is the responsibility of the "payment app". I'd split this into 2 subsections myself, the one that pertains to Payment Apps can be referenced in the Payment Handler spec.

This wouldn't specifically need a Payment Handlers spec as the browser could fulfil both roles in my mind.

Currently is doesn't have these roles and is effectively written as a "form-filler". This is inappropriate for progression to CR status IMO.

**Comment by ianbjacobs** [comment] 2017-04-03 21:47
Hi @mattsaxonwp,

The spec has been edited and the section numbers may no longer be accurate (e.g., I think 17.4 used to be 19.4).  I can't find your "section 7.4"

In reading the text of what is now 17.4, it seems to me that as written, the mediator is full responsible. One question is "where does the mediator get the data to do the things listed in 17.4?"

In the case of Web-based payment apps, we are defining a PaymentAppResponse [1]. The user agent will use it as the source of some of the information identified in 17.4 (e.g., methodName and details). 

Perhaps one way to address your comment is to add a note after the 17.4 algorithm, something like:
 
  "Note: methodName and details are provided by the user agent or other payment app."

Ian

[1] https://w3c.github.io/webpayments-payment-apps-api/#sec-payment-app-response

**Comment by mattsaxon** [comment] 2017-04-04 07:15
Yes, it's 17.4 https://w3c.github.io/browser-payment-api/#user-accepts-the-payment-request-algorithm

Your suggestion explains where the data comes from, but doesn't explain the processing and hence leaves gaps where other areas of the spec are concerned such as in [Show()](https://w3c.github.io/browser-payment-api/#show-method) which references this algorithm.

I think the algorithm need to explain at least at a high level, handover/handback to/from the payment app. This may be addressed by the discussion on extension points elsewhere.

**Comment by marcoscaceres** [comment] 2017-05-03 04:20
@mattsaxon, I'm still at a loss of what, exactly, the problem is. Having implemented this algorithm myself, I didn't encounter any issues with it. 

Can you maybe provide a code example of where you see a potential problem? Otherwise, I'm inclined to close this.

**Comment by marcoscaceres** [comment] 2017-05-03 04:27
@ianbjacobs wrote:
> "Note: methodName and details are provided by the user agent or other payment app."

The algorithm is only applicable to user agents (as they are the only class of product that conform to this specification), so the above note is redundant IMO. 

To be clear: It's only the user agent, through the IDL layer, that creates and controls the objects that participate in the "PaymentRequest updated algorithm" (or any other algorithm for that matter). Where the data comes from is not a concern of this specification, as it's always mediated through the user agent.

**Comment by mattsaxon** [comment] 2017-05-03 08:56
@marcoscaceres, please don't close. The issue is not that it is not implementable, the issue is the documentation is ambiguous and brittle as I mention above.

I've had 2 attempts at explaining this above, so I doubt a 3rd attempt will bear fruit. Could you perhaps tell me what part of my explanation is unclear and we can dig down on that. Alternatively, lets discuss on next week payment apps call (this is not urgent for FPWD.)

**Comment by marcoscaceres** [comment] 2017-05-15 07:43
Clearing CR milestone blocker, given comment above (assuming @mattsaxon meant, "urgent for CR").

We can dig into it after CR.

**Comment by marcoscaceres** [comment] 2018-01-23 04:28
Postponed until I can check how Payment Handler hooks into Payment Request here.

**Comment by ianbjacobs** [comment] 2018-01-29 21:15
Hi all,

I've submitted a pull request related to this issue:
 https://github.com/w3c/payment-request/pull/679

I will also be thinking about a tweak to canMakePayment() to acknowledge payment handlers more clearly.

**Comment by marcoscaceres** [comment] 2018-01-30 00:03
> I will also be thinking about a tweak to canMakePayment() to acknowledge payment handlers more clearly.

We just need a non-normative note saying that each payment handler spec will define what "supported" means. We don't have a clear understanding how this stuff is going to work (yet), and it's going to probably take us another few years to work it out.

**Comment by marcoscaceres** [comment] 2018-01-30 00:07
Labelled this active again (and as Editorial). Now that we actually teased out the problem and identified where wording was missing, we should be able to close this quickly. 

@mattsaxon, let us know when you are satisfied and when we can close. I think once @ianbjacobs sends in the `canMakePayment()` note, we should have everything covered - but please confirm.

**Comment by ianbjacobs** [comment] 2018-01-30 23:33
@marcoscaceres,

It seems to me that show() and canMakePayment() could address this topic in similar or even identical ways. This led me to compare the show() and canMakePayment() algorithms. I note that the show() algorithm steps 14.1-14.5 are more detailed than the similar steps of canMakePayment(), that is the single step 6.1. I am wondering whether those could be harmonized.

If so, then I think that the language of show() is pretty good for addressing this issue. It says currently:

"If the user agent has a registered payment handler that supports identifier, then check if the payment handler is authorized and capable of handling the payment request with data. If the check returns in the affirmative, then add payment handler to handlers."

In the case of canMakePayment() it might read at the end of the sequence of steps:

"If the user agent has a registered payment handler that supports identifier, then check if the payment handler is authorized and capable of handling the payment request with data. If the check returns in the affirmative, then resolve promise with true, and abort this algorithm."

Thoughts?

Also, I am inclined to add a paragraph (one sentence) to the start of 18.2 Payment Handler Matching. Something like:

"A user agent's payment handler matching algorithm takes into account the requirements of this specification as well as matching requirements defined in payment methods and other specifications."

Just to note a few of them here on GitHub:
 * Payment method specific capability matching
 * Payment method manifest authorization
 * Whether a merchant requires a 3DS flow (cf the 3DS task force; this is in development though it is still early days).

Ian

**Comment by marcoscaceres** [comment] 2018-01-31 10:33
https://github.com/w3c/payment-request/issues/535 😇

Let’s discuss there so we can close #535 too.

**Comment by ianbjacobs** [comment] 2018-02-12 15:09
Did a pull request as part of discussion:
 https://github.com/w3c/payment-request/pull/682

**Comment by stpeter** [comment] 2018-03-05 18:41
@ianbjacobs What exactly is the "matching algorithm"? We say that "a user agent can limit matching ... to payment handlers from the same origin as a URL payment method identifier" but that doesn't fully specify how matching works or even what matching is. For instance, a possible rule might be "a match occurs if the payment handler was obtained from the same origin as a URL-based payment method identifier" (I'm not sure if that's quite right, e.g., does the user agent need to keep track of the origin from which each payment handler was obtained?). How does matching work for non-URL-based payment method identifiers? What is "payment method specific capability matching" (e.g., does the user agent need to modify its matching algorithm depending on the payment method being invoked)? What is "payment method manifest authorization" (pointing to https://www.w3.org/TR/payment-method-manifest/ would help) and how is that kind of authorization different from (or a kind of) matching as defined here? What does payment _handler_ matching mean for a supplementary technique like EMVCo 3-D Secure that doesn't necessarily even define a handler but instead piggybacks on other handlers (e.g., `tokenized-card`)? Although I realize that perhaps we need to figure some of this out over time, I'm also sensing quite a bit of ambiguity here that will make life harder for implementers.

**Comment by rsolomakhin** [comment] 2018-03-05 18:50
@stpeter, I attempt to better define payment handler matching in [my pull request for Payment Handler spec](https://github.com/w3c/payment-handler/pull/170/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR921). Please take a look and let me know whether that's something that make sense.

Are you beginning to look at Payment Handlers already, or is this because of Payment Request spec mentioning the Payment Handler spec?

**Comment by stpeter** [comment] 2018-03-05 18:55
@rsolomakhin Thanks for the pointer! I haven't yet found the cycles to dig into Payment Handler. For now @marcoscaceres and I are pushing to get Payment Request done, so I'm reviewing all the CR-Exit issues. :-)

**Comment by marcoscaceres** [comment] 2018-05-01 08:35
@ianbjacobs did #682 close this?

**Comment by ianbjacobs** [comment] 2018-05-04 14:16
@marcoscaceres, thank you, I'm satisfied.

**Closed as completed** 2018-05-07 04:20 UTC
Labels: Editorial, CR-Exit
