### ISSUE TITLE
Make billing address optional

### ISSUE THREAD

**Issue by agektmr** [w3c/browser-payment-api#773] opened 2018-09-07 15:37 UTC
Looks like appending a billing address to a payment credential is not a common idea all over the world. In Japan we usually do not need one for credit card authorization.
- Some merchants don't want to take additional sensitive data which is not required.
- Credit card data usually don't come with a billing address in many cases (Chrome for example). Adding one is an extra step for easy checkouts.

I would like to propose making billing address optional by adding a new param something like:

```
dictionary PaymentOptions {
  boolean requestPayerName = false;
  boolean requestPayerEmail = false;
  boolean requestPayerPhone = false;
  boolean requestShipping = false;
  PaymentShippingType shippingType = "shipping";
  boolean requestBillingAddress = false; // New!
};
```

**Comment by romandev** [comment] 2018-09-07 16:18
I'm not sure but the billing address is already optional in spec side.
https://w3c.github.io/payment-method-basic-card/#basiccardresponse-dictionary
Am I missing something?

**Comment by marcoscaceres** [comment] 2018-09-07 16:37
Yep, duplicate of https://github.com/w3c/payment-request/pull/749/files

Got you covered, @agektmr. Will land soon!

**Closed as completed by marcoscaceres** 2018-09-07 16:37 UTC

**Comment by agektmr** [comment] 2018-09-08 13:20
Glad to learn it's already taken care of. Thanks!
