### ISSUE TITLE
PaymentAddress should be a dictionary

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#299] opened 2016-11-14 01:34 UTC
It seems that some dictionaries have been made into interfaces for the sole purpose of giving them a serializer. This seems like syntactic sugar that could be handled by developers - or is there a strong rationale for adding these serializers? I'm new, so I'm probably missing something.

**Comment by marcoscaceres** [comment] 2016-11-23 07:05
Mozilla would like to request that `PaymentAddress` be changed to a dictionary. Rationale is given above - and also because it violates principles of the extensible web manifesto: we shouldn't add new interfaces to the web platform that are not reusable primitives.  

The side effect of changing this is that `PaymentRequest`'s and `PaymentResponse`'s `shippingAddress` attribute needs to change to a method: `getShippingAddress()` which returns null or a `PaymentAddress` dictionary.

**Comment by marcoscaceres** [comment] 2016-11-24 01:54
I'm also looking at PaymentAddress as just being `FormData` instead of a Dictionary. Will play with this a bit.

**Comment by marcoscaceres** [comment] 2017-02-20 00:47
Closing this, as the API shipped and it's too late to change this.

**Comment by adrianhopebailie** [comment] 2017-02-20 09:50
> Closing this, as the API shipped and it's too late to change this.

I have a problem with that given that we are operating within the WG on the assumption that anything can still change with good enough reasons. If this is an issue that Mozilla still wishes to push at the WG meeting next month then keep it open and let's do that.

**Comment by tommythorsen** [comment] 2017-02-20 09:55
@adrianhopebailie 
> I have a problem with that given that we are operating within the WG on the assumption that anything can still change with good enough reasons. If this is an issue that Mozilla still wishes to push at the WG meeting next month then keep it open and let's do that.

I agree with Adrian. This specification is still under development, and any early implementers should be fully aware that it may change in incompatible ways. Any shipped implementation of this should be clearly marked as experimental. We should absolutely not let concerns about breaking existing implementations keep us from making the best specification we can.

**Comment by zcorpan** [comment] 2017-02-20 10:44
> Closing this, as the API shipped and it's too late to change this.

It's only shipped (enabled by default) in Chrome for Android so far, right? I think it is still reasonable to make incompatible changes, assuming the relevant implementors agree with making the change.

**Comment by msporny** [comment] 2017-02-20 15:03
> Closing this, as the API shipped and it's too late to change this.

+1 to not closing this specific issue. 

In addition, and more generally, we should not use "the API shipped" as a reason to not pursue important changes to any of the pre-PR specifications that this group is working on.

**Comment by marcoscaceres** [comment] 2017-02-20 15:48
The situation is that this API is pretty stable (basically 2 implementations and 3rd on the way), so implementers are reluctant to change stuff without a really strong reason - or in a manner that is now backwards compatible. 

There is not a strong reason to make the change I originally requested here (apart from architectural purity). 

Thus, this should be closed.

**Comment by dlongley** [comment] 2017-02-20 17:49
> There is not a strong reason to make the change I originally requested here (apart from architectural purity).
> 
> Thus, this should be closed.

If that is the reason for closing then it seems fine to me. I think the issue people had above was that the reason for closing should not be "the API shipped" at this point in the spec's development -- with which I agree.

**Comment by ianbjacobs** [comment] 2017-02-20 19:53
Given that the person who raised the issue is proposing to close it, +1 to closing it.
Ian

**Closed as completed** 2017-02-21 00:02 UTC
