### ISSUE TITLE
Should the API support field validation?

### ISSUE THREAD

**Issue by andrewagain** [w3c/browser-payment-api#225] opened 2016-08-08 17:39 UTC
It would be nice if the web page could indicate a problem with specific fields provided by the user:

Examples:
- Web page does not ship to a particular postal code
- Web page requires both a first and last name to fulfill the order
- Invalid credit card number

I am particularly interested in checks that CAN NOT be done by the user agent on it's own. For instance the user agent could check that the state/region and postal code match, but it could not know which states/regions the web page supports shipping to.

My understanding is that currently the only way to indicate invalid fields is to:
1. Web page calls `paymentResponse.complete('fail')`
2. Web page displays the error with it's own UX
3. User is required to start the payment process over from the beginning

That seems like a big headache for a user who just has to tweak one field.

Instead, I am proposing that the web page could indicate errors of various types. One idea of how this could work is with a new `validationErrors()` method on the `PaymentResponse` object:

```
paymentResponse.validationErrors([
  { field: 'shippingAddress.postalCode', message: 'Example web site does not support shipping to postal code 99999.' },
  { field: 'shippingAddress.recipient', message: 'Please provide both a first name and a last name.' },
])
```

The user agent, upon receiving these validation errors, could display a list of invalid fields along with the message for each field. The user would correct each field and then continue.

**Comment by rsolomakhin** [comment] 2016-08-08 17:56
We can also add validation errors to `PaymentDetails`, so that merchant can notify the browser during `shippingaddresschange` event.

``` javascript
payment.addEventListener('shippingaddresschange', function(evt) {
  evt.updateWith(new Promise(function(resolve) {
    if (payment.shippingAddress.postalCode === '99999') {
      details.validationErrors = [{field: 'postalCode', message: 'Example site does not support shipping to postal code 9999'}];
    } else {
      delete details.validationErrors;
    }
    resolve(details);
  }));
});
```

**Comment by adrianba** [comment] 2016-09-17 01:36
This is an interesting proposal but one that adds a fair amount of complexity. PR #257 added the ability to provide a free form error message describing the validation error as part of the `updateWith` call. I propose that the error message is sufficient for v1 and propose that we postpone this issue until we have more implementation experience.

**Comment by marcoscaceres** [comment] 2018-01-23 02:46
closing this one as duplicate of #647

**Closed as completed by marcoscaceres** 2018-01-23 02:46 UTC
