### ISSUE TITLE
Reject acceptedPromise if payment method identifer is invalid

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/browser-payment-api#557] opened 2017-06-29 15:59 UTC
Per suggestion here for consistency with fail fast design: https://github.com/w3c/browser-payment-api/pull/536#discussion_r124839099

The payment identifiers provided in a request should be valid (per the PMI spec) and can either be checked as part of the `show()` algorithm at step 11 [here](https://w3c.github.io/browser-payment-api/#show-method) or earlier at step 4.2 of the Payment Request constructor [here](https://w3c.github.io/browser-payment-api/#constructor) although this is likely more processing than desired inside a constructor.

Assuming this check is implemented in the `show()` algorithm it should result in the promise being rejected. The error to use is up for debate... 

URL parsing error seems best for a URL identifier unless the issue is specific to payment method identifiers (not using `https` etc)

**Comment by marcoscaceres** [comment] 2017-07-24 09:26
Closing as duplicate of #464.

@adrianhopebailie, I'm about to send a PR that ignores the invalid ones during construction as per #464. 

Checking what UAs do in the tests (coming also with PR).

**Closed as completed by marcoscaceres** 2017-07-24 09:26 UTC
Labels: duplicate
