### ISSUE TITLE
Do we need payment method identifier aliases?

### ISSUE THREAD

**Issue by dret** [w3c/browser-payment-api#149] opened 2016-04-21 18:30 UTC
the current draft defines/allows identifiers to be used in short or long forms. most experience with identifiers in the wild shows that no matter how clear equivalence rules are defined, they tend to be ignored, leading to problems with identifier recognition, and interoperability issues. unless there is a very compelling reason why non-unique identifiers should be supported, it may be better to forego the convenience of a shortcut notation, and always require identifiers in some canonical form.

**Comment by adrianhopebailie** [comment] 2016-04-28 20:44
Duplicate of #10

**Closed as completed by adrianhopebailie** 2016-04-28 20:44 UTC
Labels: duplicate, question, Design/Technical, Priority: High

**Comment by dret** [comment] 2016-04-29 04:32
not sure that this really is a duplicate of #10. afaict, #10 is about the need to have identifiers to begin with, whereas #149 is asking about aliases (i.e., assuming that identifiers are needed/used, but questioning whether there should be more than one way to refer to a payment method).

**Comment by adrianhopebailie** [comment] 2016-04-29 08:43
@dret - I think the group has consensus that we do need identifiers and there is now a debate about the usefulness of aliases for well-known payment methods.

I guess I could have closed #10 and kept #149 open but really that's the crux of the issue right now. I will add a comment to #10 to properly set the context.

**Comment by adrianba** [comment] 2016-04-29 12:51
My apologies for the confusing wording for #10 but it was absolutely about aliases. "well-known" means either coded into user agents or somehow otherwise special. "for ubiquitous" means that we would not do this for all methods, just those that were popular enough. I worked with @zkoch on a proposal that accounts for this feedback in #149, which we will share soon addressing #10 and #11.

**Comment by dret** [comment] 2016-04-29 16:39
sounds good, thanks.
