### ISSUE TITLE
What if the user refuses to supply a shipping address

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#279] opened 2016-09-19 09:00 UTC
The PaymentResponse interface indicates that the shippingAddress attribute of the response will contain the full and final shipping address chosen by the user.  

Do we describe the behavior of the system if the user refuses to supply an address?  If not, should we?

**Comment by adrianba** [comment] 2016-09-19 11:55
The payment request cannot be completed if `requestShipping` is `true` and no address is selected (the User accepts the payment request algorithm ensures this).

**Comment by burdges** [comment] 2016-09-19 13:43
We should expect that users will refuse to supply the shipping address to any payment apps, which might leak it to sites that do not need it, but might happily supply it to individual merchants.

**Comment by adrianba** [comment] 2016-09-19 14:02
> We should expect that users will refuse to supply the shipping address to any payment apps, which might leak it to sites that do not need it, but might happily supply it to individual merchants. 

I'm not sure we should expect that but the spec doesn't say anything about payment apps. Knowing whether a payment app is trustworthy seems like an issue for the payment apps work.

**Comment by zkoch** [comment] 2016-09-19 16:21
Agreed with @adrianba. If the user doesn't want to supply this information, they can't move forward. The PR spec doesn't say anything about Payment Apps. I don't think we need to add any text or clarification here.

**Comment by burdges** [comment] 2016-09-20 11:52
I think users should not give their browser or payment apps personally identifying information that these programs might just hand out willy nilly when they're doing things that do not require them.  In particular, a person buying digital content should not be revealing their address.  I'd imagine organizations like the EFF, etc. will be happy to add advice to this effect to various guides they maintain.

**Comment by adrianba** [comment] 2016-09-20 13:00
> In particular, a person buying digital content should not be revealing their address.

If a site asks for a shipping address and the user doesn't want to give a shipping address then they shouldn't purchase. That's what happens with forms today and it is the same with Payment Request API.

Let's close this issue - there are no changes to be made to the spec here.

**Closed as completed by adrianba** 2016-09-20 13:00 UTC

**Comment by burdges** [comment] 2016-09-20 22:05
I'm envisioning attacks like the following : 

Some browser has a scenario where it supplies the shipping address without prompting the user, like maybe the user has only ever entered one shipping address or whatever.  

We've an adversary Steve the Stalker who likes to collect celebrities' home addresses so he can go visit them.  Steve sets up an online gossip magazine that requires buying a $0.05 subscription for most content.  Steve selects the payment app to look innocuous, appear not need an address due to it being digital delivery, etc., but nevertheless sets that address is required.  I doubt Steve even needs to process any payments or posses a merchant account, so he remains anonymous.

Clever twitter usage, etc. brings in the victims.  Almost nobody bulks at paying $0.05 with a payment app that normally looks pretty secure, due to using some tokenizations or whatever.  Certainly some notice that an address is required, either because their browser asks for a first shipping address, or because it asks for them to pick one, or because they use a better browser.  But plenty fall into the scenario where no shipping address prompt occurs.

This is a completely realistic attack.  There were some Russians who doxed a bunch of Russian porn stars recently.  And most celebrities google themselves to see what is being said about them.

I think we really need a firm principle that no personal information is ever supplied without the user being reminded of that information and approving it.  Yes, I know ordinary form auto-complete already violates that principle, but some people do turn it off for that reason, and that's not a reason to make this spec insecure.  Yes, I know the attack still works if people get the habit of clicking Ok too quickly, but that's still a big reduction.

**Comment by adrianhopebailie** [comment] 2016-09-21 17:47
@burdges to be clear the shipping address data provided by the user here is never shared with payment apps.

The merchant can prompt the user to provide an address and the browser can facilitate this process and then return the data to the merchant website.

If the merchant says address is required then the process can't continue unless the user supplies an address. The user must either provide and address or cancel the payment.

**Comment by burdges** [comment] 2016-09-21 18:26
Yeah, the payment app does not really matter in this attack, but obviously some will tend to be more trustworthy than others, and some will get used for digital content which does not normally require a shipping address, so the payment app can be manipulated to give a positive impression.

The issue is : What if browser automates providing a shipping address so that the user never sees it? 

We actually cannot do anything about that because we cannot dictate UX for browsers.  We can however warn in the spec that security requires that the user should be prompted with any specific information the browser reveals.  If a browser vender ignores that warning, then Steve the Stalker or whatever is a problem of their creation, not ours.

**Comment by adrianba** [comment] 2016-09-22 13:00
> We can however warn in the spec that security requires that the user should be prompted with any specific information the browser reveals

This is already in the spec.
